/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.ControlShowPas;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.JButton;
import javax.swing.JList;

/**
 *
 * @author Muhammad Rifky Putra Ananda
 */
public class FormShowPas extends javax.swing.JFrame {

    /**
     * Creates new form FormShowPas
     */
    public FormShowPas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fieldIDP = new javax.swing.JTextField();
        BtnKembali = new javax.swing.JButton();
        BtnCariIDP = new javax.swing.JButton();
        BtnShowAll = new javax.swing.JButton();
        BtnRemovePas = new javax.swing.JButton();
        BtnRemoveAll = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPas = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaPas = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lihat Pasien", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jLabel1.setText("IDP");

        fieldIDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIDPActionPerformed(evt);
            }
        });

        BtnKembali.setText("Kembali");

        BtnCariIDP.setText("Cari");

        BtnShowAll.setText("Tampilkan Semua");

        BtnRemovePas.setText("Hapus");

        BtnRemoveAll.setText("Hapus Semua");

        listPas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listPas);

        textAreaPas.setColumns(20);
        textAreaPas.setRows(5);
        jScrollPane2.setViewportView(textAreaPas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(49, 49, 49)
                            .addComponent(fieldIDP, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BtnCariIDP, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BtnShowAll, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(BtnRemovePas, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(BtnRemoveAll, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(jScrollPane2))))
                    .addComponent(BtnKembali))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fieldIDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCariIDP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnShowAll)
                    .addComponent(BtnRemovePas)
                    .addComponent(BtnRemoveAll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(BtnKembali)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldIDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIDPActionPerformed

    public void addActionListener(ActionListener a){
        BtnCariIDP.addActionListener(a);
        BtnShowAll.addActionListener(a);
        BtnRemoveAll.addActionListener(a);
        BtnKembali.addActionListener(a);
        BtnRemovePas.addActionListener(a);
//        BtnSelesai.addActionListener(a);
    }
   
    public void addMouseAdapter(MouseAdapter m){
        listPas.addMouseListener(m);
    }
    
    //list dan text area
    public int getSelectedPasien(){
        return listPas.getSelectedIndex();
    }
    
    public void setDaftarPasien(String[] dIDP){
        listPas.setListData(dIDP);
    }
    
    public void setTextPasien(String s){
        textAreaPas.setText(s);
    }
    
    public void setList(String[] s){
        listPas.setListData(s);
    }
    
    
    //get
    public String getfieldIDP(){
        return fieldIDP.getText();
    }
    
    //button
    public JButton getBtnCariIDP() {
        return BtnCariIDP;
    }

    public JButton getBtnRemovePas() {
        return BtnRemovePas;
    }

    public JButton getBtnKembali() {
        return BtnKembali;
    }

    public JButton getBtnRemoveAll() {
        return BtnRemoveAll;
    }

//    public JButton getBtnSelesai() {
//        return BtnSelesai;
//    }

    public JButton getBtnShowAll() {
        return BtnShowAll;
    }
    
    //list
    public JList getListPas() {
        return listPas;
    }

    public void resetView(){
        fieldIDP.setText("");
        listPas.clearSelection();
        textAreaPas.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCariIDP;
    private javax.swing.JButton BtnKembali;
    private javax.swing.JButton BtnRemoveAll;
    private javax.swing.JButton BtnRemovePas;
    private javax.swing.JButton BtnShowAll;
    private javax.swing.JTextField fieldIDP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listPas;
    private javax.swing.JTextArea textAreaPas;
    // End of variables declaration//GEN-END:variables

}
