/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Asus
 */
public class FormAddDok extends javax.swing.JFrame {

    /**
     * Creates new form FormAddDok
     */
    public FormAddDok() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        labelNIP = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelUmur = new javax.swing.JLabel();
        labelGelar = new javax.swing.JLabel();
        SpinnerUmur = new javax.swing.JSpinner();
        fieldNIP = new javax.swing.JTextField();
        fieldNama = new javax.swing.JTextField();
        ComboBoxGelar = new javax.swing.JComboBox<>();
        btnAddDok = new javax.swing.JButton();
        btnCAddDok = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tambah Dokter", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        labelNIP.setText("NIP");

        labelNama.setText("Nama");

        labelUmur.setText("Umur");

        labelGelar.setText("Gelar");

        SpinnerUmur.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        fieldNIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNIPActionPerformed(evt);
            }
        });

        ComboBoxGelar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dokter Anak", "Dokter Anestesi", "Dokter Bedah", "Dokter Kandungan", "Dokter Penyakit Dalam", "Dokter THT" }));

        btnAddDok.setText("Tambah");
        btnAddDok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDokActionPerformed(evt);
            }
        });

        btnCAddDok.setText("Kembali");
        btnCAddDok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCAddDokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelUmur)
                            .addComponent(labelNIP)
                            .addComponent(labelNama)
                            .addComponent(labelGelar))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(fieldNIP, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldNama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SpinnerUmur, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ComboBoxGelar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 63, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCAddDok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddDok)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNIP)
                    .addComponent(fieldNIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNama)
                    .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUmur)
                    .addComponent(SpinnerUmur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGelar)
                    .addComponent(ComboBoxGelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddDok)
                    .addComponent(btnCAddDok))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddDokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddDokActionPerformed

    private void btnCAddDokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCAddDokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCAddDokActionPerformed

    private void fieldNIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNIPActionPerformed

    public void addActionListener(ActionListener a){
        btnAddDok.addActionListener(a);
        btnCAddDok.addActionListener(a);
    }
    
    //button
    public JButton getBtnAddDok(){
        return btnAddDok;
    }
    
    public JButton getBtnCAddDok(){
        return btnCAddDok;
    }
    
    
    public String getfieldNIP(){
        return fieldNIP.getText();
    }
    
    public String getfieldNama(){
        return fieldNama.getText();
    }
    
    public int getSpinnerUmur(){
        return (int) SpinnerUmur.getValue();
    }
    
    public int getComboBoxGelar(){
        if((String)ComboBoxGelar.getSelectedItem() == "Dokter Anak"){
           return 1; 
        }
        else if((String)ComboBoxGelar.getSelectedItem() == "Dokter Anesteti"){
            return 2;
        }
        else if((String)ComboBoxGelar.getSelectedItem() == "Dokter Bedah"){
            return 3;
        }
        
        else if((String)ComboBoxGelar.getSelectedItem() == "Dokter Kandungan"){
            return 4;
        }
        else if((String)ComboBoxGelar.getSelectedItem() == "Dokter Penyakit Dalam"){
            return 5;
        }
        else if((String)ComboBoxGelar.getSelectedItem() == "Dokter THT"){
            return 6;
        }
        return 0;
    }
    
    //reset
    public void resetView(){
        fieldNIP.setText("");
        fieldNama.setText("");
        SpinnerUmur.setValue(this);
        ComboBoxGelar.setSelectedIndex(0);
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxGelar;
    private javax.swing.JSpinner SpinnerUmur;
    private javax.swing.JButton btnAddDok;
    private javax.swing.JButton btnCAddDok;
    private javax.swing.JTextField fieldNIP;
    private javax.swing.JTextField fieldNama;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelGelar;
    private javax.swing.JLabel labelNIP;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelUmur;
    // End of variables declaration//GEN-END:variables
}
