/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Asus
 */
public class FormShowDok extends javax.swing.JFrame {

    /**
     * Creates new form FormShowDokPerIdx
     */
    public FormShowDok() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fieldNIP = new javax.swing.JTextField();
        BtnCariNIP = new javax.swing.JButton();
        BtnShowAll = new javax.swing.JButton();
        BtnRemoveDok = new javax.swing.JButton();
        BtnRemoveAll = new javax.swing.JButton();
        BtnKembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listDok = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaDok = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lihat Dokter", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jLabel1.setText("NIP");

        BtnCariNIP.setText("Cari");

        BtnShowAll.setText("Tampilkan Semua");
        BtnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnShowAllActionPerformed(evt);
            }
        });

        BtnRemoveDok.setText("Hapus");

        BtnRemoveAll.setText("Hapus Semua");

        BtnKembali.setText("Kembali");

        listDok.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listDok);

        textAreaDok.setColumns(20);
        textAreaDok.setRows(5);
        jScrollPane2.setViewportView(textAreaDok);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnKembali)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(50, 50, 50)
                        .addComponent(fieldNIP, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnCariNIP, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnShowAll, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnRemoveDok, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnRemoveAll, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2)
                                .addGap(2, 2, 2)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fieldNIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCariNIP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnShowAll)
                    .addComponent(BtnRemoveDok)
                    .addComponent(BtnRemoveAll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(BtnKembali)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnShowAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnShowAllActionPerformed

    public void addActionListener(ActionListener a){
        BtnCariNIP.addActionListener(a);
        BtnShowAll.addActionListener(a);
        BtnRemoveDok.addActionListener(a);
        BtnRemoveAll.addActionListener(a);
//        BtnSelesai.addActionListener(a);
        BtnKembali.addActionListener(a);
    }
    
    public void addMouseAdapter(MouseListener m){
        listDok.addMouseListener(m);
    }
    
    //get untuk list dan text area
    public int getSelectedDok(){
        return listDok.getSelectedIndex();
    }
    
    public void setDaftarDokter(String[] dNIP){
        listDok.setListData(dNIP);
    }
    
    public void setTextDokter(String s){
        textAreaDok.setText(s);
    }
    
    public String getfieldNIP(){
        return fieldNIP.getText();
    }
    
    //button
    public JButton getBtnCariNIP() {
        return BtnCariNIP;
    }

    public JButton getBtnKembali() {
        return BtnKembali;
    }

    public JButton getBtnRemoveAll() {
        return BtnRemoveAll;
    }

    public JButton getBtnRemoveDok() {
        return BtnRemoveDok;
    }

//    public JButton getBtnSelesai() {
//        return BtnSelesai;
//    }

    public JButton getBtnShowAll() {
        return BtnShowAll;
    }
    
    //field
    public JTextField getFieldNIP() {
        return fieldNIP;
    }
    
    //list
    public JList<String> getListDok() {
        return listDok;
    }

    public JTextArea getTextAreaDok() {
        return textAreaDok;
    }
    
    public void setList(String[] s){
        listDok.setListData(s);
    }
    
    //reset
    public void resetView(){
        fieldNIP.setText("");
        listDok.clearSelection();
        textAreaDok.setText("");
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCariNIP;
    private javax.swing.JButton BtnKembali;
    private javax.swing.JButton BtnRemoveAll;
    private javax.swing.JButton BtnRemoveDok;
    private javax.swing.JButton BtnShowAll;
    private javax.swing.JTextField fieldNIP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listDok;
    private javax.swing.JTextArea textAreaDok;
    // End of variables declaration//GEN-END:variables
}
