/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.JButton;
import javax.swing.JList;

/**
 *
 * @author Muhammad Rifky Putra Ananda
 */
public class FormShowRuangan extends javax.swing.JFrame {

    /**
     * Creates new form FormShowRuangan
     */
    public FormShowRuangan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fieldNoRuang = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BtnKembali = new javax.swing.JButton();
        BtnCariNoRuang = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listRuang = new javax.swing.JList<>();
        BtnShowAll = new javax.swing.JButton();
        BtnRemoveAll = new javax.swing.JButton();
        BtnRemoveRuangan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaRuangan = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lihat Ruangan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jLabel1.setText("No. Ruang");

        BtnKembali.setText("Kembali");

        BtnCariNoRuang.setText("Cari");

        listRuang.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listRuang);

        BtnShowAll.setText("Tampilkan Semua");

        BtnRemoveAll.setText("Hapus Semua");

        BtnRemoveRuangan.setText("Hapus");

        textAreaRuangan.setColumns(20);
        textAreaRuangan.setRows(5);
        jScrollPane2.setViewportView(textAreaRuangan);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(fieldNoRuang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnCariNoRuang, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnKembali)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnShowAll, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnRemoveRuangan, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnRemoveAll, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNoRuang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(BtnCariNoRuang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnShowAll)
                    .addComponent(BtnRemoveAll)
                    .addComponent(BtnRemoveRuangan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(BtnKembali)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   public void addActionListener(ActionListener a){
        BtnCariNoRuang.addActionListener(a);
        BtnShowAll.addActionListener(a);
        BtnRemoveAll.addActionListener(a);
        BtnKembali.addActionListener(a);
        BtnRemoveRuangan.addActionListener(a);

    }
   
    public void addMouseAdapter(MouseAdapter m){
        listRuang.addMouseListener(m);
    }
    
    //list dan text area
    public int getSelectedRuang(){
        return listRuang.getSelectedIndex();
    }
    
    public void setDaftarRuang(String[] dNoR){
        listRuang.setListData(dNoR);
    }
    
    public void setTextRuang(String s){
        textAreaRuangan.setText(s);
    }
    
    public void setList(String[] s){
        listRuang.setListData(s);
    }
    
    
    //get
    public String getfieldNoRuang(){
        return fieldNoRuang.getText();
    }
    
    //button
    public JButton getBtnCariNoRuang() {
        return BtnCariNoRuang;
    }

    public JButton getBtnRemoveRuang() {
        return BtnRemoveRuangan;
    }

    public JButton getBtnKembali() {
        return BtnKembali;
    }

    public JButton getBtnRemoveAll() {
        return BtnRemoveAll;
    }

//    public JButton getBtnSelesai() {
//        return BtnSelesai;
//    }

    public JButton getBtnShowAll() {
        return BtnShowAll;
    }
    
    //list
    public JList getListRuang() {
        return listRuang;
    }

    public void resetView(){
        fieldNoRuang.setText("");
        listRuang.clearSelection();
        textAreaRuangan.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCariNoRuang;
    private javax.swing.JButton BtnKembali;
    private javax.swing.JButton BtnRemoveAll;
    private javax.swing.JButton BtnRemoveRuangan;
    private javax.swing.JButton BtnShowAll;
    private javax.swing.JTextField fieldNoRuang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listRuang;
    private javax.swing.JTextArea textAreaRuangan;
    // End of variables declaration//GEN-END:variables
}
